# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("config.proto", :syntax => :proto3) do
    add_message "hypertrace.agent.config.v1.AgentConfig" do
      optional :service_name, :message, 1, "google.protobuf.StringValue"
      optional :reporting, :message, 2, "hypertrace.agent.config.v1.Reporting"
      optional :data_capture, :message, 3, "hypertrace.agent.config.v1.DataCapture"
      repeated :propagation_formats, :enum, 4, "hypertrace.agent.config.v1.PropagationFormat"
      optional :enabled, :message, 5, "google.protobuf.BoolValue"
      optional :javaagent, :message, 6, "hypertrace.agent.config.v1.JavaAgent"
      map :resource_attributes, :string, :string, 7
    end
    add_message "hypertrace.agent.config.v1.Reporting" do
      optional :endpoint, :message, 1, "google.protobuf.StringValue"
      optional :secure, :message, 2, "google.protobuf.BoolValue"
      optional :token, :message, 3, "google.protobuf.StringValue"
      optional :trace_reporter_type, :enum, 5, "hypertrace.agent.config.v1.TraceReporterType"
      optional :cert_file, :message, 6, "google.protobuf.StringValue"
      optional :metric_endpoint, :message, 7, "google.protobuf.StringValue"
      optional :metric_reporter_type, :enum, 8, "hypertrace.agent.config.v1.MetricReporterType"
    end
    add_message "hypertrace.agent.config.v1.Message" do
      optional :request, :message, 1, "google.protobuf.BoolValue"
      optional :response, :message, 2, "google.protobuf.BoolValue"
    end
    add_message "hypertrace.agent.config.v1.DataCapture" do
      optional :http_headers, :message, 1, "hypertrace.agent.config.v1.Message"
      optional :http_body, :message, 2, "hypertrace.agent.config.v1.Message"
      optional :rpc_metadata, :message, 3, "hypertrace.agent.config.v1.Message"
      optional :rpc_body, :message, 4, "hypertrace.agent.config.v1.Message"
      optional :body_max_size_bytes, :message, 5, "google.protobuf.Int32Value"
      optional :body_max_processing_size_bytes, :message, 6, "google.protobuf.Int32Value"
    end
    add_message "hypertrace.agent.config.v1.JavaAgent" do
      repeated :filter_jar_paths, :message, 1, "google.protobuf.StringValue"
    end
    add_enum "hypertrace.agent.config.v1.PropagationFormat" do
      value :B3, 0
      value :TRACECONTEXT, 1
    end
    add_enum "hypertrace.agent.config.v1.TraceReporterType" do
      value :UNSPECIFIED, 0
      value :ZIPKIN, 1
      value :OTLP, 2
      value :LOGGING, 3
      value :NONE, 4
    end
    add_enum "hypertrace.agent.config.v1.MetricReporterType" do
      value :METRIC_REPORTER_TYPE_UNSPECIFIED, 0
      value :METRIC_REPORTER_TYPE_OTLP, 1
      value :METRIC_REPORTER_TYPE_PROMETHEUS, 2
      value :METRIC_REPORTER_TYPE_LOGGING, 3
      value :METRIC_REPORTER_TYPE_NONE, 4
    end
  end
end

module Hypertrace
  module Agent
    module Config
      module V1
        AgentConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hypertrace.agent.config.v1.AgentConfig").msgclass
        Reporting = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hypertrace.agent.config.v1.Reporting").msgclass
        Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hypertrace.agent.config.v1.Message").msgclass
        DataCapture = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hypertrace.agent.config.v1.DataCapture").msgclass
        JavaAgent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hypertrace.agent.config.v1.JavaAgent").msgclass
        PropagationFormat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hypertrace.agent.config.v1.PropagationFormat").enummodule
        TraceReporterType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hypertrace.agent.config.v1.TraceReporterType").enummodule
        MetricReporterType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hypertrace.agent.config.v1.MetricReporterType").enummodule
      end
    end
  end
end
